[package]
name = "rust-cargo"
version = "0.1.0"
authors = ["vn7n24fzkq <vn7n24fzkq@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
