name: pre-release

workflow_run:
  workflows: ["Test and Lint"]
  types: 
    - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show project
      run: ls -a
    - name: Move to cargo project
      run: cd rust-cargo/
    - name: Build
      run: cargo build --verbose --release
