name: pre-release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tag:
        description: 'release-tags'
        required: false
        type: string

  workflow_run:
    workflows: ["Test and Lint"]
    branches: ["master"]
    types: 
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show project
      run: ls -a
    - name: Move to cargo project
      run: cd rust-cargo/
    - name: Build
      run: cargo build --verbose --release
    - name: push
      run: git add . && git commit -m ${inputs.tag}}
